# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site title
title: Practicing Data Science in Field

# A description of your site for social meta tag, search engines, and feed.xml
description: Using Data Mining, Statistical Modelling and Optimization

# Tagline near the site title
tagline: "Let's data be the truth."

# Google Analytics
google_analytics: UA-116218531-1

# The subpath of your site, e.g. /blog, for generating urls
baseurl:

sass:
  sass_dir: _sass

# The base hostname & protocol of your site for where absolute urls are needed
url: ""

# Site navigation - each item must have a title and a url.
navigation:
- text: Home
  url: /
# - text: About
#   url: /about/
# - text: Style Guides
#   url: /style-guide/
- text: Archives
  url: /tags/

# The shortname for your Disqus site to enable comments.
disqus: mineshjethva

# Author information - author info at the bottom of the post
author_name: "Minesh A. Jethva"
author_bio: "A Ph.D. researcher working on Cancer Immunology & Precision Medicine using Bioinformatics approaches. Looking forward to joining industrial career as Bioinformatics Data Scientist."
author_url:  "https://www.linkedin.com/in/mineshjethva/"
author_location: "Beersheva, Israel"
author_image: /images/Minesh.jpg

# Sidebar Add banner
banner_url: "https://www.binance.com/?ref=10265687"
banner_image: images/binance-banner.png
banner_text: "If you're looking for a serious exchange to trade crypto-currencies, I strongly vouch for <a href=\"https://www.binance.com/?ref=10265687\" target=\"_blank\">Binance</a>. I use it myself and wrote <a href=\"/2017/12/21/the-best-exchanges-to-buy-and-sell-your-cryptocurrencies\">a detailed article</a> to explain why it has become my main exchange."

# Sidebar newsletter widget - add your form action url for MailChimp signup form here
#mailchimp_url: "//inspired-beings.us4.list-manage.com/subscribe/post?u=b6cde986b53329195cc6f9d8e&amp;id=d76e394a53"

# Social links in the site footer
twitter_username: ""
# facebook_username: "username"
googleplus_username: ""
github_username: "minesh1291"
# codepen_username: "username"
# dribbble_uername: "username"
medium_username: "@MineshJ1291"
# instagram_username: "username"
# pinterest_username: "username"
linkedin_username: "mineshjethva"
# weibo_username: "username"

# http://jekyllrb.com/docs/pagination/
paginate: 5
paginate_path: '/blog/page:num/'
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag

permalink: pretty
markdown: kramdown
kramdown:
    auto_ids: false
